name: API trigger

on: repository_dispatch


jobs:

  Repo_dispatch:

    runs-on: ubuntu-latest
    steps: 
    - name: Dump GitHub context
      env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
